[package]
version = "0.1.0"
name = "blevm-common"
edition = "2021"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
celestia-types = { workspace = true }
tendermint = {workspace=true}
tendermint-proto = {workspace=true}
rsp-client-executor = {workspace=true}
nmt-rs = "*"